const landingPageInfo = [
  {
    id: 0,
    title: "Model S",
    description: "Order Online for Touchless Delivery",
    backgroundImg: "model-s.jpg",
    leftBtnText: "Custom Order",
    rightBtnText: "Existing Inventory",
  },
  {
    id: 1,
    title: "Model 3",
    description: "Order Online for Touchless Delivery",
    backgroundImg: "model-3.jpg",
    leftBtnText: "Custom Order",
    rightBtnText: "Existing Inventory",
  },
  {
    id: 2,
    title: "Model X",
    description: "Order Online for Touchless Delivery",
    backgroundImg: "model-x.jpg",
    leftBtnText: "Custom Order",
    rightBtnText: "Existing Inventory",
  },
  {
    id: 3,
    title: "Model Y",
    description: "Order Online for Touchless Delivery",
    backgroundImg: "model-y.jpg",
    leftBtnText: "Custom Order",
    rightBtnText: "Existing Inventory",
  },
  {
    id: 4,
    title: "Solar Panels",
    description: "Lowest Cost Solar Panels in America",
    backgroundImg: "solar-panel.jpg",
    leftBtnText: "Order now",
    rightBtnText: "learn more",
  },
  {
    id: 5,
    title: "Solar Roof",
    description: "Produce Clean Energy From Your Roof",
    backgroundImg: "solar-roof.jpg",
    leftBtnText: "Order now",
    rightBtnText: "learn more",
  },
  {
    id: 6,
    title: "Accessories",
    description: "",
    backgroundImg: "accessories.jpg",
    leftBtnText: "shop now",
    rightBtnText: "",
  },
];

export default landingPageInfo;
